### ISSUE TITLE
FR: show when  a note exist

### ISSUE THREAD

**Issue by deladriere** [bartkessels/daily-note-calendar#34]
Would it be possible to add an underline or some other indicator to show when a note exists, similar to the dots used in the Liamcain calendar? 

I’m not sure how complex this would be, but I believe it could be very helpful for both weekly and daily notes.

Thank you!

**Comment by bartkessels** [comment]
Thank you for your feedback!

Yes, that's a great idea. I've had it on the roadmap for quite a while, but haven't had the time to implement it. First I'm going to implement the feature request for the templating engine (the other issue that's opened) and then I'm going to implement the dots for the daily and weekly notes that exist.

Thank you for using the plugin, and if you encounter any issues or have other feature requests feel free to let me know!

**Comment by bartkessels** [comment]
Hello, just a little update. Right now I’m still working on adding support to display some kind of indicator to see which dates have notes. Bevause of the way the plugin is set up, it requires a bit of refactoring which is taking a bit longer than I expected. So I just want to let you know that I haven’t forgotten this feature request, and I hope you can still use the plugin until then.

**Comment by deladriere** [comment]
Thanks for the update keep going ! I use it all the time

**Comment by bartkessels** [comment]
Well, I have some great new. I've completed the feature request to add an indicator for days or weeks that have notes. You can also hide the indicator in the settings if you want.

I'll be creating a new release (1.8.0) to add the feature to the plugin. And again, if you have any more feedback or suggestions please let me know!

**Comment by bartkessels** [comment]
The release 1.8.0 has just been published, so from now on you can update the plugin in Obsidian. After the update, you'll have a new setting in the Daily note plugin to toggle the note indicator.

![image](https://github.com/user-attachments/assets/4096e27a-81e0-4892-a705-2175afed353d)

After that, whenever you open a new note from the calendar it will automatically update the calendar to display an indicator to all dates that already have a note.

I will close this feature request, if you face any issues at all feel free to open another issue! Have a great day and a happy new year in advance!
