### ISSUE TITLE
FR: option to set the start of the week

### ISSUE THREAD

**Issue by ksdavidc** [bartkessels/daily-note-calendar#47]
I would suggest an option to set the start of the week, such as to a particular day or what my system uses. My system uses Sunday, but DNC is using Monday, leading to confusion.

**Comment by bartkessels** [comment]
Hello, that's a good one and luckily a little easier to implement than your other ideas 😂. So, in the next release 1.10.0 you can change a setting to set your first day of week. Right now after changing the setting, you need to navigate to a next or previous month to trigger the re-render of the plugin and then the settings will take effect. This is something that I want to fix in the future.

<img width="1737" alt="Screenshot 2024-12-23 at 12 47 48" src="https://github.com/user-attachments/assets/18ba5a2e-460b-447d-91c6-6ef86b237a61" />

In the screenshot above you can see the new setting and in the background the calendar with Sunday as the first day.

**Comment by bartkessels** [comment]
The release 1.10.0 has just been created, so the next time you update the plugin you can change the start of the week to Sunday. As for your other feature requests, I'll be working on them in the upcoming weeks.
